// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gen "github.com/leabago/share-radio/adder/docs/gen"
	entity "github.com/leabago/share-radio/adder/internal/entity"
)

// MockTranslation is a mock of Translation interface.
type MockTranslation struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationMockRecorder
}

// MockTranslationMockRecorder is the mock recorder for MockTranslation.
type MockTranslationMockRecorder struct {
	mock *MockTranslation
}

// NewMockTranslation creates a new mock instance.
func NewMockTranslation(ctrl *gomock.Controller) *MockTranslation {
	mock := &MockTranslation{ctrl: ctrl}
	mock.recorder = &MockTranslationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslation) EXPECT() *MockTranslationMockRecorder {
	return m.recorder
}

// History mocks base method.
func (m *MockTranslation) History(ctx context.Context, userID string) (entity.TranslationHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "History", ctx, userID)
	ret0, _ := ret[0].(entity.TranslationHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History.
func (mr *MockTranslationMockRecorder) History(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockTranslation)(nil).History), ctx, userID)
}

// Translate mocks base method.
func (m *MockTranslation) Translate(ctx context.Context, userID string, t entity.Translation) (entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", ctx, userID, t)
	ret0, _ := ret[0].(entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationMockRecorder) Translate(ctx, userID, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslation)(nil).Translate), ctx, userID, t)
}

// MockUser is a mock of User interface.
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
}

// MockUserMockRecorder is the mock recorder for MockUser.
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance.
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// GetUser mocks base method.
func (m *MockUser) GetUser(ctx context.Context, userID string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserMockRecorder) GetUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUser)(nil).GetUser), ctx, userID)
}

// Login mocks base method.
func (m *MockUser) Login(ctx context.Context, email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserMockRecorder) Login(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUser)(nil).Login), ctx, email, password)
}

// Register mocks base method.
func (m *MockUser) Register(ctx context.Context, username, email, password string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, username, email, password)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserMockRecorder) Register(ctx, username, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUser)(nil).Register), ctx, username, email, password)
}

// MockTask is a mock of Task interface.
type MockTask struct {
	ctrl     *gomock.Controller
	recorder *MockTaskMockRecorder
}

// MockTaskMockRecorder is the mock recorder for MockTask.
type MockTaskMockRecorder struct {
	mock *MockTask
}

// NewMockTask creates a new mock instance.
func NewMockTask(ctrl *gomock.Controller) *MockTask {
	mock := &MockTask{ctrl: ctrl}
	mock.recorder = &MockTaskMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTask) EXPECT() *MockTaskMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTask) Create(ctx context.Context, userID, title, description string) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, title, description)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaskMockRecorder) Create(ctx, userID, title, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTask)(nil).Create), ctx, userID, title, description)
}

// Delete mocks base method.
func (m *MockTask) Delete(ctx context.Context, userID, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskMockRecorder) Delete(ctx, userID, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTask)(nil).Delete), ctx, userID, taskID)
}

// Get mocks base method.
func (m *MockTask) Get(ctx context.Context, userID, taskID string) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, taskID)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTaskMockRecorder) Get(ctx, userID, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTask)(nil).Get), ctx, userID, taskID)
}

// List mocks base method.
func (m *MockTask) List(ctx context.Context, userID string, status *entity.TaskStatus, limit, offset int) ([]entity.Task, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, status, limit, offset)
	ret0, _ := ret[0].([]entity.Task)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTaskMockRecorder) List(ctx, userID, status, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTask)(nil).List), ctx, userID, status, limit, offset)
}

// Transition mocks base method.
func (m *MockTask) Transition(ctx context.Context, userID, taskID string, newStatus entity.TaskStatus) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transition", ctx, userID, taskID, newStatus)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transition indicates an expected call of Transition.
func (mr *MockTaskMockRecorder) Transition(ctx, userID, taskID, newStatus interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transition", reflect.TypeOf((*MockTask)(nil).Transition), ctx, userID, taskID, newStatus)
}

// Update mocks base method.
func (m *MockTask) Update(ctx context.Context, userID, taskID, title, description string) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userID, taskID, title, description)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTaskMockRecorder) Update(ctx, userID, taskID, title, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTask)(nil).Update), ctx, userID, taskID, title, description)
}

// MockStation is a mock of Station interface.
type MockStation struct {
	ctrl     *gomock.Controller
	recorder *MockStationMockRecorder
}

// MockStationMockRecorder is the mock recorder for MockStation.
type MockStationMockRecorder struct {
	mock *MockStation
}

// NewMockStation creates a new mock instance.
func NewMockStation(ctrl *gomock.Controller) *MockStation {
	mock := &MockStation{ctrl: ctrl}
	mock.recorder = &MockStationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStation) EXPECT() *MockStationMockRecorder {
	return m.recorder
}

// CreateStation mocks base method.
func (m *MockStation) CreateStation(ctx context.Context, request gen.CreateStationRequestObject) (gen.StationId, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStation", ctx, request)
	ret0, _ := ret[0].(gen.StationId)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStation indicates an expected call of CreateStation.
func (mr *MockStationMockRecorder) CreateStation(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStation", reflect.TypeOf((*MockStation)(nil).CreateStation), ctx, request)
}

// GetStation mocks base method.
func (m *MockStation) GetStation(ctx context.Context, request gen.GetStationRequestObject) (gen.StationDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStation", ctx, request)
	ret0, _ := ret[0].(gen.StationDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStation indicates an expected call of GetStation.
func (mr *MockStationMockRecorder) GetStation(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStation", reflect.TypeOf((*MockStation)(nil).GetStation), ctx, request)
}

// ListStations mocks base method.
func (m *MockStation) ListStations(ctx context.Context, request gen.ListStationsRequestObject) (gen.StationListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStations", ctx, request)
	ret0, _ := ret[0].(gen.StationListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStations indicates an expected call of ListStations.
func (mr *MockStationMockRecorder) ListStations(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStations", reflect.TypeOf((*MockStation)(nil).ListStations), ctx, request)
}

// MockGenre is a mock of Genre interface.
type MockGenre struct {
	ctrl     *gomock.Controller
	recorder *MockGenreMockRecorder
}

// MockGenreMockRecorder is the mock recorder for MockGenre.
type MockGenreMockRecorder struct {
	mock *MockGenre
}

// NewMockGenre creates a new mock instance.
func NewMockGenre(ctrl *gomock.Controller) *MockGenre {
	mock := &MockGenre{ctrl: ctrl}
	mock.recorder = &MockGenreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenre) EXPECT() *MockGenreMockRecorder {
	return m.recorder
}

// ListGenres mocks base method.
func (m *MockGenre) ListGenres(ctx context.Context, request gen.ListGenresRequestObject) (gen.GenreList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGenres", ctx, request)
	ret0, _ := ret[0].(gen.GenreList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGenres indicates an expected call of ListGenres.
func (mr *MockGenreMockRecorder) ListGenres(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGenres", reflect.TypeOf((*MockGenre)(nil).ListGenres), ctx, request)
}

// MockLanguage is a mock of Language interface.
type MockLanguage struct {
	ctrl     *gomock.Controller
	recorder *MockLanguageMockRecorder
}

// MockLanguageMockRecorder is the mock recorder for MockLanguage.
type MockLanguageMockRecorder struct {
	mock *MockLanguage
}

// NewMockLanguage creates a new mock instance.
func NewMockLanguage(ctrl *gomock.Controller) *MockLanguage {
	mock := &MockLanguage{ctrl: ctrl}
	mock.recorder = &MockLanguageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLanguage) EXPECT() *MockLanguageMockRecorder {
	return m.recorder
}

// ListLanguages mocks base method.
func (m *MockLanguage) ListLanguages(ctx context.Context, request gen.ListLanguagesRequestObject) (gen.ListLanguagesResponseObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLanguages", ctx, request)
	ret0, _ := ret[0].(gen.ListLanguagesResponseObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLanguages indicates an expected call of ListLanguages.
func (mr *MockLanguageMockRecorder) ListLanguages(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLanguages", reflect.TypeOf((*MockLanguage)(nil).ListLanguages), ctx, request)
}
